name: Update GitHub Activity
on:
  schedule:
    - cron: "0 * * * *" # updates every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JamesIves/github-activity-readme@v0.3.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
